### ISSUE TITLE
Build script cannot find "intl.lib" / "libintl.h"

### ISSUE THREAD

**Issue by jobegrabber** [wingtk/gtk-win32#59]
Trying to build with 
`C:\gtk-build\github\gtk-win32>python .\build.py build --perl-dir "C:\strawberry\perl\bin\perl.exe" --msys-dir "C:\msys2" --nuget-path "C:\ProgramData\chocolatey\bin\NuGet.exe" --patches-root-dir "C:\gtk-build\github\gtk-win32" --clean --vs-ver 14 -p x64 gtk3`

results in

```
Building project glib
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(1189,5): warning MSB8012: TargetPath(C:\gtk-build\build\x64\release\glib\bui
ld\win32\vs14\Release\x64\bin\glib.dll) does not match the Linker's OutputFile
property value (C:\gtk-build\build\x64\release\glib\build\win32\vs14\Release\x6
4\bin\glib-2.0.dll). This may cause your project to build incorrectly. To corre
ct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) proper
ty values match the value specified in %(Link.OutputFile). [C:\gtk-build\build\
x64\release\glib\build\win32\vs14\glib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(1191,5): warning MSB8012: TargetName(glib) does not match the Linker's Outpu
tFile property value (glib-2.0). This may cause your project to build incorrect
ly. To correct this, please make sure that $(OutDir), $(TargetName) and $(Targe
tExt) property values match the value specified in %(Link.OutputFile). [C:\gtk-
build\build\x64\release\glib\build\win32\vs14\glib.vcxproj]
  glib.vcxproj -> C:\gtk-build\build\x64\release\glib\build\win32\vs14\Release\
  x64\bin\glib.dll
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(1189,5): warning MSB8012: TargetPath(C:\gtk-build\build\x64\release\glib\bui
ld\win32\vs14\Release\x64\bin\gmodule.dll) does not match the Linker's OutputFi
le property value (C:\gtk-build\build\x64\release\glib\build\win32\vs14\Release
\x64\bin\gmodule-2.0.dll). This may cause your project to build incorrectly. To
 correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt)
property values match the value specified in %(Link.OutputFile). [C:\gtk-build\
build\x64\release\glib\build\win32\vs14\gmodule.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(1191,5): warning MSB8012: TargetName(gmodule) does not match the Linker's Ou
tputFile property value (gmodule-2.0). This may cause your project to build inc
orrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $
(TargetExt) property values match the value specified in %(Link.OutputFile). [C
:\gtk-build\build\x64\release\glib\build\win32\vs14\gmodule.vcxproj]
LINK : fatal error LNK1181: Eingabedatei "intl.lib" kann nicht ge÷ffnet werden.
 [C:\gtk-build\build\x64\release\glib\build\win32\vs14\gmodule.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(1189,5): warning MSB8012: TargetPath(C:\gtk-build\build\x64\release\glib\bui
ld\win32\vs14\Release\x64\bin\gthread.dll) does not match the Linker's OutputFi
le property value (C:\gtk-build\build\x64\release\glib\build\win32\vs14\Release
\x64\bin\gthread-2.0.dll). This may cause your project to build incorrectly. To
 correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt)
property values match the value specified in %(Link.OutputFile). [C:\gtk-build\
build\x64\release\glib\build\win32\vs14\gthread.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(1191,5): warning MSB8012: TargetName(gthread) does not match the Linker's Ou
tputFile property value (gthread-2.0). This may cause your project to build inc
orrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $
(TargetExt) property values match the value specified in %(Link.OutputFile). [C
:\gtk-build\build\x64\release\glib\build\win32\vs14\gthread.vcxproj]
LINK : fatal error LNK1181: Eingabedatei "intl.lib" kann nicht ge÷ffnet werden.
 [C:\gtk-build\build\x64\release\glib\build\win32\vs14\gthread.vcxproj]
LINK : fatal error LNK1181: Eingabedatei "intl.lib" kann nicht ge÷ffnet werden.
 [C:\gtk-build\build\x64\release\glib\build\win32\vs14\glib-genmarshal.vcxproj]
  gspawn-win32-helper.c
c:\gtk-build\build\x64\release\glib\glib\glibintl.h(16): fatal error C1083: Dat
ei (Include) kann nicht geöffnet werden: "libintl.h": No such file or directory
 [C:\gtk-build\build\x64\release\glib\build\win32\vs14\gspawn-win32-helper.vcxp
roj]
  gspawn-win32-helper-console.c
c:\gtk-build\build\x64\release\glib\glib\glibintl.h(16): fatal error C1083: Dat
ei (Include) kann nicht geöffnet werden: "libintl.h": No such file or directory
 [C:\gtk-build\build\x64\release\glib\build\win32\vs14\gspawn-win32-helper-cons
ole.vcxproj]
Traceback (most recent call last):
  File ".\build.py", line 1235, in build
    self.__build_one(p)
  File ".\build.py", line 1275, in __build_one
    proj.build()
  File ".\build.py", line 460, in build
    self.exec_msbuild(r'build\win32\vs%(vs_ver)s\glib.sln /p:PythonPath=%(python
_dir)s', configuration=configuration)
  File ".\build.py", line 126, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(m
sbuild_opts)s', add_path=add_path)
  File ".\build.py", line 121, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_
path)
  File ".\build.py", line 1348, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_p
ath, env=self.vs_env)
  File ".\build.py", line 1380, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'msbuild build\win32\vs14\glib.sln /p:PythonPath=c:\
Python27 /p:Configuration=Release_BundledPCRE /nologo /p:Platform=x64   /v:minim
al' returned non-zero exit status 1
Error: glib build failed
```

I installed every possible libintl package in MSYS2, no success.

Any pointers where

**Comment by jobegrabber** [comment]
Nevermind, I oversaw that there's no support for VS2015/VS14
